ssh -f supcon@10.64.1.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.2.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.3.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.4.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.5.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.6.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.7.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.8.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.9.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.10.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.11.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.12.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.13.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.14.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.15.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.16.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.17.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.18.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.19.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.20.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.21.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.22.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.23.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.24.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.25.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.26.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.27.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.70.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.80.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null
ssh -f supcon@10.64.81.12 sh /home/supcon/supconsys/bin/startall \&> /dev/null